### ISSUE TITLE
inconsistent behaviour of redirects

### ISSUE THREAD

**Issue by MildlyInterested** [hallowelt/docker-bluespice-free#8]
1. with this docker compose
```yml
version: '3.3'
services:
    bluespice-free:
        ports:
            - '8089:80'
        volumes:
            - "/path/bluespice/:/data"
        environment:
            - bs_lang=en
            - "bs_url=http://192.168.0.12:8089/wiki"
        image: bluespice/bluespice-free
        network_mode: "bridge"
```
2. Accessing `http://192.168.0.12:8089/wiki` displays error 404 from nginx.
![image](https://user-images.githubusercontent.com/57712666/194714087-1142e780-a060-4619-ae47-dd43d1984426.png)
3. Accessing `http://192.168.0.12:8089` redirects to `http://192.168.0.12:80/wiki`.
4. Changing the address manually to `http://192.168.0.12:8089/wiki` will then display the "login required screen" from bluespice.
5. Clicking login will redirect to "localhost/...." address, replacing localhost once more with `http://192.168.0.12:8089/...` will show the actual login screen.
6. After successfull login you get dropped to `http://localhost/wiki/Main_Page`, changing that manually once more shows the actual main page.
7. After that most things seem to link correctly, although some random settings also bring you back to `localhost/...` (e.g. "enhanced upload")

**Comment by Jonty16117** [comment]
In the environment variables, you are providing the port number along with the url. So ideally if you want to map local port along with the url, your environment variables in your case would be something like these:
```yaml
version: '3.3'
services:
    bluespice-free:
        ports:
            - 8089:80
        volumes:
            - "/path/bluespice/:/data"
        environment:
            - bs_lang=en
            - bs_url=192.168.0.12
        image: bluespice/bluespice-free
        network_mode: "bridge"
```
